version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env  
    environment:
      - REACT_APP_NEWSAPI_KEY=${REACT_APP_NEWSAPI_KEY}
      - REACT_APP_NYT_API_KEY=${REACT_APP_NYT_API_KEY}
      - REACT_APP_GUARDIAN_API_KEY=${REACT_APP_GUARDIAN_API_KEY}
      

